language: php
dist: precise

php:
    - 5.3
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1

matrix:
    exclude:
        - php: 7.0
          env: WP_VERSION=4.1 WP_MULTISITE=0
        - php: 7.0
          env: WP_VERSION=4.1 WP_MULTISITE=1

before_script:
    - bash tools/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test
